# permissions for end users to edit registries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: registry-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: registry-operator
    app.kubernetes.io/part-of: registry-operator
    app.kubernetes.io/managed-by: kustomize
  name: registry-editor-role
rules:
- apiGroups:
  - registry-operator.dev
  resources:
  - registries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - registry-operator.dev
  resources:
  - registries/status
  verbs:
  - get
